name: nifty_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  fluttertoast: ^8.2.2
  cached_network_image: ^3.2.0
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  internet_connection_checker: ^1.0.0+1
  get_storage: ^2.1.1
  date_format: ^2.0.7
  google_fonts: ^6.1.0
  another_xlider: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_speed_dial: ^7.0.0
  flutter_typeahead: ^5.0.1
  flutter_hooks: ^0.20.3
  collection: ^1.17.2
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1
  animations: ^2.0.8
  country_flags: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  image: assets/images/logo.png
  color: "5E92F3"
  android_disable_fullscreen: true


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter: 
  uses-material-design: true
  assets:
    - assets/images/