// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOlwG4mKbq82ttd90iQjmrFdRNsjTP2M',
    appId: '1:528380706090:web:259e0b767491ca5b20b253',
    messagingSenderId: '528380706090',
    projectId: 'httpstheniftydietcom',
    authDomain: 'httpstheniftydietcom.firebaseapp.com',
    storageBucket: 'httpstheniftydietcom.appspot.com',
    measurementId: 'G-8S4P2JN4NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDODHYukNd-HTT5F4bkB6Qncq7HBqekVFw',
    appId: '1:528380706090:android:e8edff3a935030a720b253',
    messagingSenderId: '528380706090',
    projectId: 'httpstheniftydietcom',
    storageBucket: 'httpstheniftydietcom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WPHGQdi9CdGV_QP6JMmcbpUAMV9dStM',
    appId: '1:528380706090:ios:1497b0bc0db9ff7e20b253',
    messagingSenderId: '528380706090',
    projectId: 'httpstheniftydietcom',
    storageBucket: 'httpstheniftydietcom.appspot.com',
    iosBundleId: 'com.uni-do.niftyIos',
  );

}