// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtKy6AU8Y-41HGHdiCHCeLaWzusMqWL0',
    appId: '1:114474626621:web:d5d8df03fed61af8a60454',
    messagingSenderId: '114474626621',
    projectId: 'nifty-diet',
    authDomain: 'nifty-diet.firebaseapp.com',
    storageBucket: 'nifty-diet.appspot.com',
    measurementId: 'G-1813JM4F4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU4m-mYpZxS0nR4Gnavnex_9GYoj5FrHM',
    appId: '1:114474626621:android:f0a8246c276b46cba60454',
    messagingSenderId: '114474626621',
    projectId: 'nifty-diet',
    storageBucket: 'nifty-diet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-7Rfu265JRLxn82QvJRxgnvagpHN868',
    appId: '1:114474626621:ios:ae39a81b8f56ee00a60454',
    messagingSenderId: '114474626621',
    projectId: 'nifty-diet',
    storageBucket: 'nifty-diet.appspot.com',
    iosBundleId: 'com.uni-do.niftyIos',
  );
}
